### ISSUE TITLE
function in className property confuses indentation

### ISSUE THREAD

**Issue by erfanio** [MaxMEllon/vim-jsx-pretty#17] opened 2017-03-11 22:12 UTC
I have classname to combine classnames in my className props in react and it makes the indentation incorrect.

Incorrect
![image](https://cloud.githubusercontent.com/assets/9994172/23827264/a21f9c72-0703-11e7-92f8-b807f0fc8792.png)
(a lot of code has been removed to make the issue immediately visible)

without classname, correct
![image](https://cloud.githubusercontent.com/assets/9994172/23827270/e6efb49a-0703-11e7-8ce7-7ed688b8d5f1.png)

all of these are indented by just pressing =

**Comment by erfanio** [comment] 2017-03-11 22:19
There seem to be more indentation issues

if i put my return in a function it's indented incorrectly
![image](https://cloud.githubusercontent.com/assets/9994172/23827309/df388384-0704-11e7-8ab6-b2c124df0a8c.png)

but outside of the if statement it is indented correctly
![image](https://cloud.githubusercontent.com/assets/9994172/23827311/f78978d0-0704-11e7-82ab-538e73529a44.png)

**Comment by MaxMEllon** [comment] 2017-03-12 06:31
I can't reproduce the error.

![l](https://cloud.githubusercontent.com/assets/9594376/23829571/b12c6af8-0738-11e7-942f-a10338a17ea8.gif)

Please show me plugin list of your vim.

**Comment by MaxMEllon** [comment] 2017-03-12 06:33
I can't reproduce the error.

![l](https://cloud.githubusercontent.com/assets/9594376/23829589/352bec84-0739-11e7-984c-6899564b9bb7.gif)

Please show me plugin list of your vim.

**Comment by yuezk** [comment] 2018-11-29 06:05
I can't reproduce it as well, close it for the time being.

**Closed by yuezk** 2018-11-29 06:05 UTC
