### ISSUE TITLE
Option to only work on `.jsx` files

### ISSUE THREAD

**Issue by snoblenet** [MaxMEllon/vim-jsx-pretty#85] opened 2019-08-27 07:03 UTC
Is there a way to configure this to *only* work on `.jsx` files?

For now I've just manually removed every instance of `typescript.vim` from my local copy of the plugin to stop it from deciding that TypeScript type references surrounded by triangle brackets in my `.ts` files are actually embedded JSX.

**Comment by yuezk** [comment] 2019-08-27 07:10
So, you mean it affects the typescript syntax highlighting? Why not provide the reproducible code and I will take an investigation?

**Comment by yuezk** [comment] 2019-11-04 07:24
@snoblenet I'm closing this issue since I have added the `g:vim_jsx_pretty_disable_tsx` option to disable this plugin on typescript files in #98. You can change it to `1` to disable this plugin on typescript files.

**Closed** 2019-11-04 07:24 UTC

**Comment by AerynHachey** [comment] 2019-12-11 20:32
A better fix would be to disable it in just .ts files rather than .tsx. .tsx files are .ts files that will contain jsx, and thus want jsx highlighting. .ts files normally don't contain jsx, and would want this plugin to ignore them to avoid breaking highlighting.

The root of the issue seems to be that Typescript uses triangular brackets to cast objects. Example:

`foo(<any>bar);`

This gets picked up as the start of jsx, and breaks highlighting on everything in the document after `<any>`.

**Comment by yuezk** [comment] 2019-12-12 23:29
@AerynHachey I see, will take a look later.

**Comment by yuezk** [comment] 2019-12-19 15:25
Hi, @AerynHachey, highlighting for `foo(<any>bar);` seems has been fixed in #114.
